name: Build and Release Game

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v1.1.0, etc.
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name "Adventure_Game" main.py
        
    - name: Create release assets
      run: |
        mkdir release-assets
        copy dist\Adventure_Game.exe release-assets\
        copy README.md release-assets\
        copy LICENSE release-assets\ 2>nul || echo "No LICENSE file found"
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release-assets/*
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload executable artifact
      uses: actions/upload-artifact@v3
      with:
        name: Adventure_Game_Executable
        path: dist/Adventure_Game.exe
